package main.utility;

public enum TileType {
    EMPTY,
    CLASH,
    WALL,
    YELLOW_GROWER,
    YELLOW_GROWER_NEW,
    YELLOW_BASIC,
    YELLOW_BASIC_NEW,
    YELLOW_ADVANCED,
    YELLOW_ADVANCED_SNAKE,
    YELLOW_FUSE,
    YELLOW_FUSE_SNAKE,
    RED_GROWER,
    RED_GROWER_NEW,
    RED_BASIC,
    RED_BASIC_NEW,
    RED_ADVANCED,
    RED_ADVANCED_SNAKE,
    RED_FUSE,
    RED_FUSE_SNAKE
}
